config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('game/', include('game.urls')),
]

game/urls.py
from django.urls import path

from . import views

app_name = 'game'

urlpatterns = [
    path('<str:league_name>/search_for_opponent_ajax/', views.SearchForOpponentAjaxView.as_view(), name='search_for_opponent_ajax'),
    path('<str:league_name>/cancel_ajax/', views.CancelAjaxView.as_view(), name='cancel_ajax'),
    path('<str:league_name>/search_for_opponent/', views.SearchForOpponentView.as_view(), name='search_for_opponent'),
    path('<str:league_name>/room/<str:room_name>/', views.RoomView.as_view(), name='room'),
    path('enroll/<str:league_name>/', views.CreateResultTableView.as_view(), name='create_result_table'),
    path('league_list/', views.LeagueListView.as_view(), name='league_list'),
    path('create_league/', views.CreateLeagueView.as_view(), name='create_league'),
    path('<str:league_name>/ranking/', views.RankingView.as_view(), name='ranking'),
    path('result_list/', views.ResultListView.as_view(), name='result_list'),
    path('check_league_name_ajax/', views.CheckLeagueNameAjax.as_view(), name='check_league_name_ajax'),
    path('league_filter_ajax/', views.LeagueFilterViewAjax.as_view(), name='league_filter_ajax'),
    path('get_game_ajax/', views.GetGameAjaxView.as_view(), name='get_game_ajax'),
    path('', views.HomeView.as_view(), name='home'),
]

game/models.py
from django.db import models
from django.conf import settings
import uuid
from django.urls import reverse
from django.utils import timezone
import json



class LeagueCategory(models.Model):
    name = models.CharField(max_length=50, verbose_name='リーグカテゴリ')
    players = models.ManyToManyField(settings.AUTH_USER_MODEL, verbose_name='参加者', blank=True)
    details = models.TextField(verbose_name='詳細', blank=True)
    host = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT, related_name='league_category', verbose_name='主催者')
    start_at = models.DateTimeField(verbose_name='開始日時')
    finish_at = models.DateTimeField(verbose_name='終了日時')
    created_at = models.DateTimeField(verbose_name='登録日時', default=timezone.now)
    participants = models.IntegerField(verbose_name='参加人数', default=0)


    def __str__(self):
        return self.name

class ResultTable(models.Model):
    player = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='player', related_name='result_table')
    league = models.ForeignKey(LeagueCategory, on_delete=models.CASCADE, verbose_name='リーグカテゴリ', related_name='result_table')
    dp = models.DecimalField(verbose_name='dp', default=0, max_digits=6, decimal_places=1)
    win = models.PositiveIntegerField(verbose_name='勝ち数', default=0)
    loose = models.PositiveIntegerField(verbose_name='負け数', default=0)
    game_num = models.PositiveIntegerField(verbose_name='試合数', default=0)
    rank = models.PositiveIntegerField(verbose_name='順位', default=1)

    def __str__(self):
        return "{} - {}".format(self.player, self.league)

    def get_absolute_url(self):
        return reverse('game:search_for_opponent', kwargs={"league_name": self.league.name})


class WaitingPlayer(models.Model):
    player = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='player', related_name='waiting_player')
    league = models.ForeignKey(LeagueCategory, on_delete=models.CASCADE, verbose_name='リーグカテゴリ', related_name='waiting_player')
    dp = models.PositiveIntegerField(verbose_name='dp', default=0)

    def __str__(self):
        return "{} - {}".format(self.player, self.league)


def default_result():
    result = {
        'player1': '',
        'player2': '',
        'thema': '',
        'win_rate12': 0.5,
        'win_rate21': 0.5,
    }
    return json.dumps(result)

class Game(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4
    )
    league = models.ForeignKey(LeagueCategory, on_delete=models.CASCADE, related_name='game', verbose_name='リーグカテゴリ')
    room = models.CharField(max_length=200, verbose_name='room名', unique=True)
    player1 = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT, related_name='game_player1', verbose_name='player1')
    player2 = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT, related_name='game_player2', verbose_name='player2')
    result = models.JSONField(verbose_name='試合結果', default=default_result)
    start_at = models.DateTimeField(verbose_name='開始日時', default=timezone.now)
    submitted_players = models.ManyToManyField(settings.AUTH_USER_MODEL, verbose_name='結果提出者')
    win_rate12 = models.DecimalField(max_digits=11, decimal_places=10, default=0.5)
    win_rate21 = models.DecimalField(max_digits=11, decimal_places=10, default=0.5)

    def __str__(self):
        return "{} vs {} at {}".format(self.player1, self.player2, self.start_at.strftime("%Y/%m/%d %H:%M:%S"))


class ChatMessage(models.Model):
    content = models.TextField(verbose_name='チャットメッセージ', max_length=200)
    game = models.ForeignKey(Game, on_delete=models.CASCADE, related_name='chat_message', verbose_name='試合')
    posted_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT, related_name='chat_message', verbose_name='投稿者')
    timestamp = models.DateTimeField(verbose_name='投稿時刻', default=timezone.now)

    def __str__(self):
        return "{} by {} ({})".format(self.content[:10], self.posted_by, self.game)

game/forms.py
from django import forms

from . import models


class CreateResultTableForm(forms.ModelForm):

    class Meta:
        model = models.ResultTable
        fields = ['league', ]

game/views.py
import json, time, random, string, secrets, math
from unicodedata import name
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.views import generic
from django.db import transaction
from django.db.models import Q
from django.contrib.auth import mixins, get_user_model
from django.urls import reverse
from django.contrib import messages
from django.utils import timezone

from . import models, forms, view_models

class HomeView(generic.TemplateView):
    template_name = 'home.html'


class SearchForOpponentView(mixins.LoginRequiredMixin, generic.TemplateView):
    template_name = 'game/search_for_opponent.html'

    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        league = models.LeagueCategory.objects.get(name=self.kwargs.get('league_name'))
        try:
            result = models.ResultTable.objects.get(player=self.request.user, league=league)
        except models.ResultTable.DoesNotExist:
            return HttpResponseRedirect(reverse('game:create_result_table', kwargs={"league_name": league.name}))
        game = models.Game.objects.filter(league=league).filter(Q(player1=self.request.user)|Q(player2=self.request.user)).exclude(submitted_players=self.request.user).distinct()
        if game.exists():
            messages.warning(self.request, "結果を入力してください")
            return HttpResponseRedirect(reverse('game:room', kwargs={"league_name": game[0].league, "room_name": game[0].room}))
        context.update({'league': league, 'result': result})
        return self.render_to_response(context)

    def post(self, request, *args, **kwargs):
        return HttpResponseRedirect(reverse('game:search_for_opponent'))

class CancelAjaxView(mixins.LoginRequiredMixin, generic.View):
    def post(self, request, *args, **kwargs):
        league_name = self.kwargs.get('league_name')
        self.league = models.LeagueCategory.objects.get(name=league_name)
        try:
            models.WaitingPlayer.objects.get(player=self.request.user, league=self.league).delete()
        except models.WaitingPlayer.DoesNotExist:
            pass
        return JsonResponse({'message': "対戦を中止しました"})


class SearchForOpponentAjaxView(mixins.LoginRequiredMixin, generic.View):
    matching_range = 10000 #! matchingの際の±dp範囲
    dp_diff = 40000 #! 期待勝率が10倍になるであろうdp差

    def post(self, request, *args, **kwargs):
        self.start_time = time.time()
        league_name = self.kwargs.get('league_name')
        self.league = models.LeagueCategory.objects.get(name=league_name)
        self.dp = models.ResultTable.objects.get(player=self.request.user, league=self.league).dp
        models.WaitingPlayer.objects.get_or_create(player=self.request.user, league=self.league, dp=self.dp)
        opponent = self.search_for_opponent(0)
        if opponent == 'matched':
            try:
                game = models.Game.objects.exclude(submitted_players=self.request.user).get(player2=self.request.user, league=self.league)
            except models.Game.DoesNotExist:
                return JsonResponse({"message": "対戦を中止しました"})
            messages.success(self.request, "対戦相手が決定しました!")
            return JsonResponse({"is_success": True, "roomname": game.room})
        elif opponent:
            with transaction.atomic():
                waiting1 = models.WaitingPlayer.objects.get(player=self.request.user, league=self.league)
                waiting2 = models.WaitingPlayer.objects.get(player=opponent, league=self.league)
                waiting1.delete()
                waiting2.delete()
                opponent_dp = models.ResultTable.objects.get(player=opponent, league=self.league).dp
                win_rate12 = 1 / (1 + math.pow(10, (opponent_dp - self.dp) / self.dp_diff))
                while True:
                    roomname = self.generate_room()
                    if not models.Game.objects.filter(room=roomname).exists():
                        break
                game = models.Game.objects.create(
                    room=roomname,
                    player1=self.request.user,
                    player2=opponent,
                    league=self.league,
                    win_rate12=win_rate12,
                    win_rate21=1 - win_rate12
                )
            messages.success(self.request, "対戦相手が決定しました!")
            return JsonResponse({"is_success": True, "roomname": game.room})
        else:
            return JsonResponse({"is_success": False, "roomname": None, 'message': '対戦相手が見つかりませんでした'})

    def search_for_opponent(self, count):
        if not models.WaitingPlayer.objects.filter(player=self.request.user, league=self.league).exists():
            return 'matched'
        if time.time() - self.start_time >= 30.0:
            models.WaitingPlayer.objects.filter(player=self.request.user, league=self.league).delete()
            return False
        lowwer_dp, upper_dp = self.dp - self.matching_range, self.dp + self.matching_range
        opponent_candidates = models.WaitingPlayer.objects.filter(league=self.league, dp__gte=lowwer_dp, dp__lte=upper_dp).exclude(player=self.request.user).distinct()
        if not opponent_candidates.exists():
            time.sleep(0.5)
            return self.search_for_opponent(count+1)
        ind = random.randint(0, opponent_candidates.count()-1)
        opponent = opponent_candidates[ind]
        return opponent.player

    def generate_room(self):
        alphabet = string.ascii_letters + string.digits
        return ''.join(secrets.choice(alphabet) for _ in range(10))


class RoomView(mixins.LoginRequiredMixin, generic.TemplateView):
    template_name = 'game/room.html'
    ero_rate_const = 2000

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        room_name = self.kwargs.get('room_name')
        self.game = models.Game.objects.get(room=room_name)
        result = json.loads(self.game.result)['player1' if self.request.user == self.game.player1 else 'player2']
        chat_messages = models.ChatMessage.objects.filter(game=self.game).order_by('-timestamp')
        opponent = self.game.player2 if self.request.user == self.game.player1 else self.game.player1
        context.update({"game": self.game, 'chat_messages': chat_messages, 'result': result, 'opponent': opponent})
        return context

    def post(self, request, *args, **kwargs):
        self.game = models.Game.objects.get(room=self.kwargs.get('room_name'))
        self.league = self.game.league
        self.result_table = models.ResultTable.objects.get(player=self.request.user, league=self.league)
        result_num = self.request.POST.get('result')
        player = 'player1' if self.request.user == self.game.player1 else 'player2'
        if self.request.user in self.game.submitted_players.all():
            #*更新処理
            self.reset_dp(json.loads(self.game.result, player))
        else:
            #*新規作成
            self.game.submitted_players.add(self.request.user)
        self.update_dp(result_num, self.game.result, player)
        self.update_result(result_num, player)
        return HttpResponseRedirect(reverse("game:search_for_opponent", kwargs={"league_name": self.league}))

    def reset_dp(self, results, player):
        result = results[player]
        win_rate = 0.5
        if player == 'player1': win_rate = self.game.win_rate12
        else: win_rate = self.game.win_rate21
        if 'WIN' == result:
            self.result_table.dp += -self.ero_rate_const * (1 - win_rate)
            self.result_table.win += -1
        elif 'LOOSE' == result:
            self.result_table.dp += self.ero_rate_const * (-win_rate)
            self.result_table.loose += -1
        else:
            self.result_table.dp += self.ero_rate_const * (0.5 - win_rate)
        self.result_table.game_num += -1
        self.result_table.dp = max(0, self.result_table.dp)
        self.result_table.save()

    def update_dp(self, result_num, result, player):
        win_rate = 0.5
        if player == 'player1': win_rate = self.game.win_rate12
        else: win_rate = self.game.win_rate21
        if result_num == '0':
            self.result_table.dp += self.ero_rate_const * (1 - win_rate)
            self.result_table.win += 1
            messages.info(self.request, "dp +{:.1f}".format(self.ero_rate_const * (1 - win_rate)))
        elif result_num == '1':
            self.result_table.dp += self.ero_rate_const * (-win_rate)
            self.result_table.loose += 1
            messages.info(self.request, "dp {:.1f}".format(self.ero_rate_const * (-win_rate)))
        else:
            self.result_table.dp += self.ero_rate_const * (0.5 - win_rate)
            if 0.5 > win_rate:
                messages.info(self.request, "dp +{:.1f}".format(self.ero_rate_const * (0.5 - win_rate)))
            elif 0.5 < win_rate:
                messages.info(self.request, "dp {:.1f}".format(self.ero_rate_const * (0.5 - win_rate)))
            else:
                messages.info(self.request, "dp {:.1f}".format(self.ero_rate_const * (0.5 - win_rate)))
        self.result_table.dp = max(0, self.result_table.dp)
        self.result_table.game_num += 1
        self.result_table.save()

    def update_result(self, result_num, player):
        result = json.loads(self.game.result)
        RESULT_CHAR = {'0': 'WIN', '1': 'LOOSE', '2': 'DRAW'}
        result[player] = RESULT_CHAR[result_num]
        self.game.result = json.dumps(result)
        self.game.save()


class CreateResultTableView(mixins.LoginRequiredMixin, generic.CreateView):
    model = models.ResultTable
    template_name = 'game/create_result_table.html'
    form_class = forms.CreateResultTableForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        league_name = self.kwargs.get('league_name')
        league = models.LeagueCategory.objects.get(name=league_name)

templates/game/create_league.html
{% extends '_base.html' %}


{% block title %}
    リーグ追加
{% endblock title %}


{% block extra_css %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <link rel="stylesheet" type="text/css" href="https://npmcdn.com/flatpickr/dist/themes/material_blue.css">
{% endblock extra_css %}


{% block content %}
    <h3 class="mb-3">リーグ登録</h3>
    <form action="" method="post">
        {% csrf_token %}
        <div class="form-floating mb-3">
            <!-- <input type="text" class="form-control" id="id_host" name="host" disabled value="{{ user }}"> -->
            <select name="host" id="id_host" class="form-control" disabled>
                <option value="{{ user.pk }}">{{ user.username }}</option>
            </select>
            <label for="id_host">主催者</label>
        </div>
        <div class="form-floating mb-3">
            <input type="text" class="form-control" id="id_name" name="name" required placeholder="リーグ名">
            <label for="id_name">リーグ名</label>
            <small id="id_name_help" style="font-size: smaller;"></small>
        </div>
        <div class="row gx-1 mb-3">
            <div class="form-floating mb-2 col-sm-6">
                <input type="text" name="start_at" id="id_start_at" class="form-control" required>
                <label for="id_start_at">開始日時</label>
            </div>
            <div class="form-floating mb-2 col-sm-6">
                <input type="text" name="finish_at" id="id_finish_at" class="form-control" required>
                <label for="id_finish_at">終了日時</label>
            </div>
        </div>
        <textarea name="details" id="id_details" rows="4" class="form-control mb-3" placeholder="詳細"></textarea>
        <button type="submit" class="btn btn-primary">登録</button>
    </form>
{% endblock content %}


{% block extra_js %}
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
<script src="https://cdn.jsdelivr.net/npm/flatpickr/dist/l10n/ja.js"></script>
<script type="text/javascript">
    flatpickr("#id_start_at", {
        'locale': 'ja',
        minDate: "today",
        enableTime: true,
        //inline: true,
    });
    flatpickr("#id_finish_at", {
        'locale': 'ja',
        minDate: "today",
        enableTime: true,
        //inline: true,
    });


    function check_league_name(){
        $.ajax({
            type: "get",
            url: "{% url 'game:check_league_name_ajax' %}",
            dataType: "json",
            data: {
                'league_name': $("#id_name").val(),
            },
            success: function(data){
                const is_ok = data['is_ok'];
                const help_text = data['help_text'];
                if(is_ok){
                    $("#id_name_help").text(help_text);
                    $("#id_name_help").addClass("text-success");
                    $("#id_name_help").removeClass("text-danger");
                }
                else{
                    $("#id_name_help").text(help_text);
                    $("#id_name_help").removeClass("text-success");
                    $("#id_name_help").addClass("text-danger");
                }
            }
        })
    }

    $("#id_name").change(function(e){
        check_league_name();
    });

    $("#id_name").keyup(function(e){
        check_league_name();
    });
    $("#id_name").keydown(function(e){
        check_league_name();
    });

</script>

{% endblock extra_js %}

templates/game/create_result_table.html
{% extends '_base.html' %}


{% block title %}
    参加登録
{% endblock title %}


{% block content %}
    <h3>参加リーグ選択</h3>
    <p>{{ league }}に参加しますか？</p>
    <form action="" method="post">
        {% csrf_token %}
        <select class="form-select" id="id_league" name="league" hidden>
            <option value="{{ league.pk }}">{{ league }}</option>
        </select>
        <button type="submit" class="btn btn-primary">参加</button>
    </form>

{% endblock content %}

templates/game/ranking.html
{% extends '_base.html' %}
{% load game %}

{% block title %}
    順位表
{% endblock title %}


{% block content %}
    <div class="table-responsive">
        <table class="table table-striped table-hover table-responsive-md">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">プレイヤー</th>
                    <th scope="col">DP</th>
                    <th scope="col">試合数</th>
                    <th scope="col">勝数</th>
                    <th scope="col">負数</th>
                </tr>
            </thead>
            <tbody>
                {% for object in object_list %}
                    <tr class="text-start">
                        <th scope="row">{{ object.rank }}</th>
                        <td>{% if object.player.socialaccount_set.all %}<img src="{{ object.player.socialaccount_set.all.0.get_avatar_url }}" width="25px" height="25px" class="rounded-circle align-bottom">{% else %}<i class="bi bi-person-lines-fill align-middle mx-1"></i>{% endif %}&ThickSpace;<span class="link-primary">{{ object.player.username }}</span></td>
                        <td>{{ object.dp }}</td>
                        <td>{{ object.game_num }}</td>
                        <td>{{ object.win }}</td>
                        <td>{{ object.loose }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>



<!-- *PAGINATION -->
<nav class="d-flex justify-content-center">
    <ul class="pagination pagination-sm" id="pagination_ul">
        {% if current_page != 1 %}
        <li class="page-item"><a class="page-link" id="first_page" href="?{% url_replace request 'page' 1 %}">&laquo;</a></li>
        {% else %}
        <li class="page-item"><a class="page-link text-muted" id="first_page">&laquo;</a></li>
        {% endif %}

        {% for page in page_nums %}
        {% if page == current_page %}
        <li class="page-item active" id='pagination_template'>
            <a class="page-link page-num">{{ page }}</a>
        </li>
        {% else %}
        <li class="page-item" id='pagination_template'>
            <a class="page-link page-num" href="?{% url_replace request 'page' page %}">{{ page }}</a>
        </li>
        {% endif %}
        {% endfor %}

        {% if current_page != max_page %}
        <li class="page-item"><a id="last_page" class="page-link" href="?{% url_replace request 'page' max_page %}">&raquo;</a></li>
        {% else %}
        <li class="page-item"><a id="last_page" class="page-link text-muted">&raquo;</a></li>
        {% endif %}
    </ul>
</nav>

<!-- */PAGINATION  -->

{% endblock content %}

templates/game/search_for_opponent.html
{% extends '_base.html' %}
{% load static %}

{% block title %}
    対戦相手を探す
{% endblock title %}



{% block content %}
<div class="alert alert-info collapse p-1" id="failed_message">
    <!-- <span>対戦相手が見つかりませんでした。</span> -->
</div>
<h2>対戦相手を探す</h2>
<small class="text-muted" id="dp_display">
    現在のdp : {{ result.dp }}
</small>
<form action="" method="post" class="my-3">
    {% csrf_token %}
    <div class="input-group mb-3">
        <label for="id_league" class="input-group-text">参加リーグ</label>
        <select class="form-select"  id="id_league" name="league" disabled>
            <option value="{{ league.pk }}">{{ league }}</option>
        </select>
    </div>
    <button class="btn btn-primary" id="search_for_opponent" type="submit">対戦相手を探す</button>
    <button class="btn btn-danger collapse" id="cancel_btn" type="submit">キャンセル</button>
</form>
<p class="text-muted" id="matching_message"></p>


{% endblock content %}


{% block extra_js %}
<script src="{% static 'js/for_ajax_csrf.js' %}"></script>
<script>
    const failed_message = document.getElementById('failed_message');
    function search_for_opponent(){
        $.ajax({
            type: "post",
            url: "{% url 'game:search_for_opponent_ajax' league_name %}",
            dataType: "json",
            data: {
                'league_name': "{{ league_name }}",
            },
            success: function(data){
                const is_success = data['is_success'];
                const roomName = data['roomname'];
                console.log(data['roomname']);
                $("#matching_message").text("");
                if(!is_success){
                    const message = data['message'];
                    failed_message.classList.add("show");
                    failed_message.innerHTML = "<span>" + message + "</span>";
                    $("#cancel_btn").removeClass('show');
                    $("#search_for_opponent").removeClass('collapse');
                    clearInterval(timerId);
                }
                else{
                    window.location.pathname = 'game/' + "{{ league_name }}" + '/room/' + roomName + '/';
                    console.log("{% url 'game:room' league_name 123456 %}".replace(/123456/, roomName));
                }
            }
        });
    }

    function cancel(){
        $.ajax({
            type: "post",
            url: "{% url 'game:cancel_ajax' league_name %}",
            dataType: "json",
            data: {
            },
            success: function(data){
                console.log(data['message']);
            }
        })
    }

    let timerId = null;
    function display_time(start_time=30){
        document.getElementById('matching_message').textContent = "対戦相手を探しています... 00:" + start_time;
        if(start_time===0) clearInterval(timerId);
        timerId = setTimeout(display_time, 1000, start_time - 1);
    }

    $("#search_for_opponent").click(function(e){
        e.preventDefault();
        $(this).addClass('collapse');
        $("#failed_message").removeClass('show');
        $("#cancel_btn").addClass("show");
        display_time();
        search_for_opponent();
    });

    $("#cancel_btn").click(function(e){
        e.preventDefault();
        $(this).removeClass('show');
        $("#search_for_opponent").removeClass('collapse');
        cancel();
        $("#matching_message").text("");
        clearInterval(timerId);
    });
</script>
{% endblock extra_js %}