config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('game/', include('game.urls')),
]

game/urls.py
from django.urls import path

from . import views

app_name = 'game'

urlpatterns = [
    path('<str:league_name>/search_for_opponent_ajax/', views.SearchForOpponentAjaxView.as_view(), name='search_for_opponent_ajax'),
    path('<str:league_name>/cancel_ajax/', views.CancelAjaxView.as_view(), name='cancel_ajax'),
    path('<str:league_name>/search_for_opponent/', views.SearchForOpponentView.as_view(), name='search_for_opponent'),
    path('<str:league_name>/room/<str:room_name>/', views.RoomView.as_view(), name='room'),
    path('enroll/<str:league_name>/', views.CreateResultTableView.as_view(), name='create_result_table'),
    path('league_list/', views.LeagueListView.as_view(), name='league_list'),
    path('create_league/', views.CreateLeagueView.as_view(), name='create_league'),
    path('<str:league_name>/ranking/', views.RankingView.as_view(), name='ranking'),
    path('result_list/', views.ResultListView.as_view(), name='result_list'),
    path('check_league_name_ajax/', views.CheckLeagueNameAjax.as_view(), name='check_league_name_ajax'),
    path('league_filter_ajax/', views.LeagueFilterViewAjax.as_view(), name='league_filter_ajax'),
    path('get_game_ajax/', views.GetGameAjaxView.as_view(), name='get_game_ajax'),
    path('', views.HomeView.as_view(), name='home'),
]

templates/_base.html
{% load static %}
<!doctype html>
<html lang="ja">
    <!-- *HEAD  -->
    <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- *CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    {% block extra_css %}{% endblock extra_css %}
    <!-- */CSS -->

    <!-- *TITLE -->
    <title>{% block title %}{% endblock title %}</title>
    <!-- */TITLE -->
    </head>
    <!-- */HEAD  -->

    <!-- *BODY -->
    <body>
        <div class="d-flex" style="min-height: 100vh;">

            <!-- *NAV -->
            <nav class="col-md-auto navbar navbar-expand-md navbar-dark bg-dark flex-column p-0">
                <div class="collapse navbar-collapse flex-column mx-2">
                    <ul class="navbar-nav flex-column">
                        <li class="navbar-item mb-3"><a href="{% url 'game:home' %}" class="nav-link"><h2>Rating Duel</h2></a></li>
                        <li class="navbar-item mb-1">
                            <a href="#collapseGame" data-bs-toggle="collapse" class="nav-link"><i class="bi bi-trophy"></i>&ThickSpace; 試合</a>
                            <div class="collapse show" id="collapseGame">
                                <ul>
                                    <li><a href="{% url 'game:league_list' %}" class="nav-link">リーグ一覧</a></li>
                                    <li><a href="{% url 'game:create_league' %}" class="nav-link">リーグ開催</a></li>
                                </ul>
                            </div>
                        </li>
                        <li class="navbar-item mb-1">
                            <a href="#collapseData" data-bs-toggle="collapse" class="nav-link"><i class="bi bi-bar-chart-line"></i>&ThickSpace; データ</a>
                            <div class="collapse show" id="collapseData">
                                <ul>
                                    <li><a href="{% url 'game:result_list' %}" class="nav-link">結果一覧</a></li>
                                </ul>
                            </div>
                        </li>
                    </ul>
                </div>

                <!-- *OFF CANVAS -->
                <div class="offcanvas offcanvas-start w-75 bg-dark" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel">
                    <div class="offcanvas-header">
                        <h5 class="offcanvas-title nav-link" id="offcanvasExampleLabel"><a href="{% url 'game:home' %}" class="text-light" style="text-decoration: none;">Rating Duel</a></h5>
                        <button type="button" class="btn-close btn-close-white text-reset" data-bs-dismiss="offcanvas" aria-label="Close" id="offcanvas_close_btn"></button>
                    </div>
                    <div class="offcanvas-body">
                        <form action="" class="input-group mb-3" id="offcanvas_search_form">
                            <input type="search" name="offcanvas_search_key" placeholder="Search..." value="{{ search_key }}" class="form-control">
                            <button type="submit" id="offcanvas_search_btn" class="input-group-text btn btn-outline-light"><i class="bi bi-search"></i>&ThickSpace;検索</button>
                        </form>
                        <ul class="px-0 list-unstyled">
                            <li class="navbar-item mb-1">
                                <a href="#offcanvasGame" data-bs-toggle="collapse" class="nav-link text-light"><i class="bi bi-trophy"></i>&ThickSpace; 試合</a>
                                <div class="collapse show" id="offcanvasGame">
                                    <ul>
                                        <li><a href="{% url 'game:league_list' %}" class="nav-link text-light">リーグ一覧</a></li>
                                        <li><a href="{% url 'game:create_league' %}" class="nav-link text-light">リーグ開催</a></li>
                                    </ul>
                                </div>
                            </li>
                            <li class="navbar-item mb-1">
                                <a href="#offcanvasData" data-bs-toggle="collapse" class="nav-link text-light"><i class="bi bi-bar-chart-line"></i>&ThickSpace; データ</a>
                                <div class="collapse show" id="offcanvasData">
                                    <ul>
                                        <li><a href="{% url 'game:result_list' %}" class="nav-link text-light">結果一覧</a></li>
                                    </ul>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
                <!-- */OFFCANVAS -->
            </nav>
            <!-- */NAV -->

            <div class="flex-fill">
                <!-- *HEADER -->
                <header class="d-flex bg-primary justify-content-between p-2">
                    <a id="offcanvas_link" class="btn btn-primary d-md-none" data-bs-toggle="offcanvas" href="#offcanvasExample" role="button" aria-controls="offcanvasExample">
                        <i class="bi bi-list"></i>
                    </a>
                    <div class="flex-nowrap gx-1 col-auto">
                        {% include 'search_form.html' %}
                    </div>
                    <div class="dropdown">
                        <button class="col-auto btn btn-primary" id="dropdownUserMenu" data-bs-toggle="dropdown"><i class="bi bi-caret-down-fill"></i>&ThickSpace;
                            {% if user.is_authenticated %}
                                {{ user.username }}&ThickSpace;
                                {% if user.socialaccount_set.all.0.get_avatar_url %}
                                    <img src="{{ user.socialaccount_set.all.0.get_avatar_url }}" width="25px" height="25px" class="rounded-circle align-bottom">
                                {% else %}
                                    <i class="bi bi-person-lines-fill"></i>
                                {% endif %}
                            {% else %}
                                Guest&ThickSpace;<i class="bi bi-person-lines-fill"></i>
                            {% endif %}
                        </button>
                        <ul class="dropdown-menu dropdown-menu-dark">
                            {% if user.is_authenticated %}
                                <li><a href="" class="dropdown-item"><i class="bi bi-person-fill"></i>&ThickSpace;マイページ</a></li>
                                <li><a href="" class="dropdown-item"><i class="bi bi-gear-fill"></i>&ThickSpace;設定</a></li>
                                <li><hr class="dropdown-divider"></li>
                                <li><a href="{% url 'account_logout' %}" class="dropdown-item"><i class="bi bi-door-closed-fill"></i>&ThickSpace;ログアウト</a></li>
                            {% else %}
                                <li><a href="{% url 'account_login' %}" class="dropdown-item"><i class="bi bi-door-open-fill"></i>&ThickSpace;ログイン</a></li>
                                <li><hr class="dropdown-divider"></li>
                                <li><a href="{% url 'account_signup' %}" class="dropdown-item"><i class="bi bi-person-plus-fill"></i>&ThickSpace;サインアップ</a></li>
                            {% endif %}
                        </ul>
                    </div>
                </header>
                <!-- */HEADER -->

                <!-- *MAIN CONTENT -->
                <div class="container-fluid my-3">
                    {% for message in messages %}
                        <div class="alert alert-{{ message.tags }} p-1" role="alert" style="transition: all .3s;">
                            <span>{{ message }}</span>
                            <!-- <button type="button" class="btn-close align-bottom"></button> -->
                        </div>
                    {% endfor %}
                    {% block content %}{% endblock content %}
                </div>
                <!-- */MAIN CONTENT -->
            </div>
        </div>
    <!-- *SCRIPT -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    {% block extra_js %}{% endblock extra_js %}
    <!-- */SCRIPT -->
    </body>
    <!-- */BODY -->
</html>

templates/home.html
{% extends '_base.html' %}


{% block title %}
    Rating Duel
{% endblock title %}



{% block content %}
    <h2 class="mb-3">Rating Duel (&beta;)</h2>
    <div class="container">
        <div class="row mb-3 border rounded p-2">
            <h3>このサイトについて</h3>
            <div>
                このサイトはマスターデュエルやデュエルリンクスでのルーム戦を使用し、レート戦を行うためのものです。<br>
                <a href="https://twitter.com/kinghalo_dl" target="_blank">kighaloさん</a>のtwitterでの提案を見て、勝手に作らせていただきました。<br>
                バグや要望などがあれば、<a href="https://twitter.com/tokud_duellinks" target="_blank">とくD</a>にDMやマシュマロでお知らせください。
            </div>
        </div>
        <div class="row mb-3 border rounded p-2">
            <h3 class="">このサイトの使用方法</h3>
            <div>
                基本的な流れは
                <ol>
                    <li>対戦相手を探す</li>
                    <li>マッチングした相手とチャットページでやりとりし、ルーム戦を行う</li>
                    <li>対戦後、結果を入力</li>
                </ol>
                という感じです。<br>
                このサイトでは、ユーザーが各々好きなレギュレーションでリーグを開催することができ、マッチングは同一リーグ内で行われます。<br>
                大会などでの使用も大歓迎です。
            </div>
        </div>
        <div class="row mb-3 border rounded p-2">
            <h3>レーティングについて</h3>
            <div class="mb-2">
                このサイトでのポイント名は、デュエルリンクスでのKCを参考にDPとしました。<br>
                また、レートの計算についてですが、簡単に説明すると対戦相手とのレート差によって勝敗後のレート変動が決まります。<br>
                相手が自分より格上であればあるほど、勝って得られるポイントは多く、負けて失うポイントは少なくなります。
            </div>
        </div>
        <div class="row mb-3 border rounded p-2">
            <h3>&beta;版について</h3>
            <div>
                このサイトは現在&beta;版です。<br>
                バグの確認や修正、新機能の追加など、これからも進めていく予定ですので完成版はもうしばらくお待ちください。
            </div>
        </div>
    </div>
{% endblock content %}

templates/pagination.html
{% load game %}

<!-- *PAGINATION -->
<nav class="d-flex justify-content-center">
    <ul class="pagination pagination-sm">
        {% if page_obj.has_previous %}
            <li class="page-item"><a href="?{% url_replace request 'page' page_obj.previous_page_number %}" class="page-link">&laquo;</a></li>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <li class="page-item active"><a href="" class="page-link">{{ num }}</a></li>
            {% else %}
                <li class="page-item"><a href="?{% url_replace request 'page' num %}" class="page-link">{{ num }}</a></li>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <li class="page-item"><a href="?{% url_replace request 'page' page_obj.next_page_number %}" class="page-link">&raquo;</a></li>
        {% endif %}
    </ul>
</nav>
<!-- */PAGINATION  -->

templates/search_form.html
<form action="" class=" input-group d-none d-md-flex" id="header_search_form">
    <input type="search" name="search_key" placeholder="Search..." value="{{ search_key }}" class="form-control">
    <div class="btn-group" role="group">
        <button type="submit" id="search_btn" class="input-group-text btn btn-dark"><i class="bi bi-search"></i>&ThickSpace;検索</button>
    </div>
</form>